@startuml
!include style.puml

node "Couche Frontend\n<size:10>Interface utilisateur</size>" as front
node "Couche Backend\n<size:10>Logique métier</size>" as back
database "Couche Base de données\n<size:10>Persistance</size>" as db

front <--> back
back <--> db
@enduml
