@startuml
!include style.puml

enum ProjetType {
    PFE
    MEMOIRE
    STAGE
}

class Projet {
    + int id
    + string titre
    + string description
    + ProjetType type
    + string statut
}

class Etudiant {
    + string cne
    + string filiere
    + string niveau
}

class Enseignant {
    + string grade
    + string specialite
    + string departement
    + consulterConvocations()
    + getDisponibilites()
}

class Soutenance {
    + int id
    + date datePassage
    + time heureDebut
    + int dureeMinutes
    + SoutenanceStatus statut
    + planifier()
    + annuler()
}

Etudiant "1..*" -- "1" Projet : possède
Enseignant "1..*" -- "*" Projet : encadre
Projet "1" -- "1" Soutenance : fait l'objet de

@enduml
