@startuml
!theme pfe from .

enum RoleEnum {
    ADMINISTRATEUR
    COORDINATEUR
    ENSEIGNANT
    ETUDIANT
}

enum JuryRole {
    PRESIDENT
    RAPPORTEUR 
    EXAMINATEUR
    ENCADRANT
}

abstract class Utilisateur {
    + int id
    + string nom
    + string prenom
    + string email
    + string motDePasse
    + RoleEnum role
    + boolean actif
    + seConnecter(email, password)
    + seDeconnecter()
    + modifierProfil()
}

class Administrateur {
    + gererComptes()
    + configurerSalles()
    + definirPeriodes()
}

class Coordinateur {
    + creerSession()
    + validerPlanning()
    + genererDocuments()
}

class Enseignant {
    + string grade
    + string specialite
    + string departement
    + consulterConvocations()
    + getDisponibilites()
}

class Etudiant {
    + string cne
    + string filiere
    + string niveau
}

class MembreJury {
    + JuryRole roleJury
    + boolean present
}

Utilisateur <|-- Administrateur
Utilisateur <|-- Coordinateur
Utilisateur <|-- Enseignant
Utilisateur <|-- Etudiant
Enseignant <|-- MembreJury

@enduml
