@startuml
!include style.puml

enum ProjetType {
    PFE
    MEMOIRE
    STAGE
}

class Projet {
    + int id
    + string titre
    + string description
    + ProjetType type
    + string statut
}

class Etudiant {

}

class Enseignant {

}

class Soutenance {
    + int id
    + date datePassage
    + time heureDebut
    + int dureeMinutes
    + SoutenanceStatus statut
    + planifier()
    + annuler()
}

Etudiant --> Projet : possède
Enseignant --> Projet : encadre
Projet --> Soutenance : fait l'objet de

@enduml
