<style>
  root {
    FontColor #000000
    LineColor #003366
    LineThickness 1
    Margin 5
  }
  node {
    BackgroundColor #F2F4F7
    LineColor #003366
    LineThickness 1
    RoundCorner 5
    SeparatorColor #003366
  }
  class {
    BackgroundColor #F2F4F7
    HeaderBackgroundColor #003366
    FontColor #000000
    HeaderFontColor #FFFFFF
    LineThickness 1
    SeparatorColor #003366
  }
  actor {
    BackgroundColor #F2F4F7
    LineColor #003366
  }
  usecase {
    BackgroundColor #F2F4F7
    LineColor #003366
  }
  component {
    BackgroundColor #F2F4F7
    LineColor #003366
    Padding 10
  }
  database {
    BackgroundColor #F2F4F7
    LineColor #003366
  }
  rectangle {
    LineColor #003366
    RoundCorner 5
  }
  arrow {
    LineColor #003366
    FontColor #003366
  }
  package {
    BackgroundColor white
    LineColor #003366
    LineThickness 1
  }
  note {
    BackgroundColor #FEFFDD
    LineColor #003366
  }
  activity {
    BackgroundColor #F2F4F7
  }
  diamond {
    BackgroundColor #003366
    LineColor #003366
    FontColor #FFFFFF
  }
  circle {
    BackgroundColor #003366
    LineColor #003366
  }
  stop {
    BackgroundColor #003366
    LineColor #003366
  }
</style>

' Skinparams global
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam actorStyle rectangle
skinparam roundcorner 5
skinparam Padding 5
skinparam defaultFontName "SansSerif"
skinparam defaultFontSize 12
