@startuml
!include style.puml
left to right direction

actor "Utilisateur" as User
actor "Administrateur" as Admin
actor "Coordinateur" as Coord
actor "Enseignant / Membre de jury" as Jury
actor "Étudiant" as Student

Admin --|> User
Coord --|> User
Jury --|> User
Student --|> User

User -> (S'authentifier)
@enduml
