@startuml
!theme pfe from .

skinparam rectangle {
    FontSize 18
    BackgroundColor #F2F4F7
    BorderColor #003366
    BorderStyle dashed
}

left to right direction

actor "Administrateur" as Admin
actor "Coordinateur" as Coord
actor "Enseignant / Membre de jury" as Jury
actor "Étudiant" as Student

rectangle "Système de gestion des soutenances" as System {
}
 
Admin --> System
Coord --> System
Jury --> System
Student --> System

@enduml
