useCaseDiagram
    actor Admin as "Administrateur (Technique)"
    
    package "Système de Gestion des Soutenances" {
        usecase UC1 as "Configurer l'instance (Setup Wizard)"
        usecase UC2 as "Gérer les comptes utilisateurs"
        usecase UC3 as "Maintenir le référentiel (Salles/Dépts)"
    }
    
    Admin --> UC1
    Admin --> UC2
    Admin --> UC3