useCaseDiagram
    actor Student as "Étudiant"
    
    package "Système de Gestion des Soutenances" {
        usecase UC11 as "Vérifier les informations du projet"
        usecase UC12 as "Télécharger sa convocation officielle"
        usecase UC13 as "Consulter son résultat final"
    }
    
    Student --> UC11
    Student --> UC12
    Student --> UC13